//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar_To_ImageUrl
    {
        public int Id { get; set; }
        public int Avatar_Id { get; set; }
        public int ImageUrl_Id { get; set; }
    }
}
