//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avatar
    {
        public int Id { get; set; }
        public string AuthorName { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public string FolderName { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> ImagesUrl_Id { get; set; }
        public Nullable<int> Tag_Id { get; set; }
        public Nullable<int> SharePoint { get; set; }
    }
}
